[project]
name = "worlddesigner"
authors = [{name = "chadders"}]
version = "0.1.0"
description = "Create or edit levels for The World"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.2.1",
    "wxpython>=4.2.3",
]
